language: haskell
sudo: false
ghc:
  - "7.8"
  - "7.10"
  - "8.0"
install: |
  cd prototype
  cabal install --only-dependencies --enable-tests
script: |
  cd prototype
  cabal configure --enable-tests && cabal build && cabal test
